# syntax=docker/dockerfile:1

FROM docker.io/livedemo/livedemo-backend:monq-base

ENV CI=true
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

WORKDIR /home/app

COPY package.json pnpm-lock.yaml ./
COPY . ./

RUN npm install -g pnpm@10.27.0

RUN pnpm install 

RUN chmod +x start.sh

ENTRYPOINT ["./start.sh"]
